language: php
php:
  - 5.4
  - 5.5
  - hhvm

env:
  - PHPUNIT_VERSION=~3.5
  - PHPUNIT_VERSION=~3.6
  - PHPUNIT_VERSION=~3.7
  - PHPUNIT_VERSION=master

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar require phpunit/phpunit $PHPUNIT_VERSION
  - php composer.phar install --dev

script:
  - phpunit --configuration phpunit-unit.xml.dist
  - phpunit --configuration phpunit-integration.xml.dist

notifications:
  email:
    - lstrojny@php.net

matrix:
  allow_failures:
    - php: hhvm
