language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer install

script:
  - vendor/bin/phpunit --configuration phpunit-unit.xml.dist
  - vendor/bin/phpunit --configuration phpunit-integration.xml.dist

matrix:
  allow_failures:
    - php: hhvm
