language: php
php:
  - 5.4
  - 5.5
  - hhvm

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev

script:
  - phpunit --configuration phpunit-unit.xml
  - phpunit --configuration phpunit-integration.xml

notifications:
  email:
    - lstrojny@php.net

matrix:
  allow_failures:
    - php: hhvm
